package io.veloo.app.feature.speedtest

data class ResultadoSpeedtest(
    val timestampEpochMs: Long,
    val specVersion: String,
    val modo: ModoSpeedtest,
    val connectionTypeStart: String?,
    val connectionTypeEnd: String?,
    val contaminado: Boolean,
    val latenciaMs: Double,
    val jitterMs: Double,
    val perdaPercentual: Double,
    val bufferbloatMs: Double,
    val severidadeBufferbloat: SeveridadeBufferbloat,
    val downloadMbps: Double,
    val uploadMbps: Double,
    val latencyDownloadMs: Double,
    val latencyUploadMs: Double,
    val stabilityScore: Double,
    val peakDownloadMbps: Double,
    val peakUploadMbps: Double,
    val packetLossSource: String,
    val dnsLatencyMs: Int?,
    val dnsResolverIp: String?,
    val dnsProvider: String?,
    val diagnosticoQualidade: DiagnosticoQualidadeSpeedtest,
    val diagnosticoFases: DiagnosticoFasesSpeedtest,
    val uploadNaoDetectado: Boolean = false,
    val connectionType: String? = null,
    val tecnologia: String? = null,
)
